"""Full-database backup and restore.

Generic and table-agnostic — walks db.metadata rather than a hand-maintained
table list, so a new table added anywhere in the app is automatically
included next time without this file needing an update. Table order is
SQLAlchemy's own foreign-key-safe topological sort (db.metadata.sorted_tables),
used as-is for restore inserts and reversed for wipe deletes.

Security/system tables are deliberately excluded from every backup — see
EXCLUDED_TABLES. Restore logic lives in restore.py, next to this file.
"""
import io
import zipfile
import pandas as pd
from app import db

EXCLUDED_TABLES = {
    'users',               # password hashes — never belongs in a downloadable file
    'role_permissions',    # tied to the live permission system, not "business data"
    'settings',            # SMS/API keys — sensitive
    'settings_audit_logs',
    'error_logs',          # transient diagnostic data
    'notifications', 'notification_reads',  # transient, regenerated by app activity
    'sms_logs',             # message content/phone numbers — not core business records
}


def backup_tables():
    """Tables to include, in FK-safe (parents-first) order."""
    return [t for t in db.metadata.sorted_tables if t.name not in EXCLUDED_TABLES]


def _table_rows(table):
    """All rows of a table as a list of plain dicts."""
    result = db.session.execute(table.select())
    return [dict(row._mapping) for row in result]


def _table_frame(table):
    rows = _table_rows(table)
    if rows:
        return pd.DataFrame(rows)
    return pd.DataFrame(columns=[c.name for c in table.columns])


def export_backup_excel():
    """Multi-sheet Excel workbook, one sheet per table. Returns a BytesIO."""
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine='openpyxl') as writer:
        for table in backup_tables():
            df = _table_frame(table)
            # Excel sheet names are capped at 31 characters.
            df.to_excel(writer, index=False, sheet_name=table.name[:31])
    buf.seek(0)
    return buf


def export_backup_zip():
    """ZIP archive with one CSV per table. Returns a BytesIO."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        for table in backup_tables():
            df = _table_frame(table)
            zf.writestr(f'{table.name}.csv', df.to_csv(index=False))
    buf.seek(0)
    return buf
